[2024-11-17T22:19:34.809+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_to_gold_dag.upload_raw_data_to_bronze manual__2024-11-17T22:19:32.747734+00:00 [queued]>
[2024-11-17T22:19:34.814+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_to_gold_dag.upload_raw_data_to_bronze manual__2024-11-17T22:19:32.747734+00:00 [queued]>
[2024-11-17T22:19:34.814+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-11-17T22:19:34.823+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_raw_data_to_bronze> on 2024-11-17 22:19:32.747734+00:00
[2024-11-17T22:19:34.826+0000] {standard_task_runner.py:57} INFO - Started process 185 to run task
[2024-11-17T22:19:34.828+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bronze_to_gold_dag', 'upload_raw_data_to_bronze', 'manual__2024-11-17T22:19:32.747734+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmp8w9kmsl4']
[2024-11-17T22:19:34.830+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask upload_raw_data_to_bronze
[2024-11-17T22:19:34.840+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-17T22:19:34.867+0000] {task_command.py:410} INFO - Running <TaskInstance: bronze_to_gold_dag.upload_raw_data_to_bronze manual__2024-11-17T22:19:32.747734+00:00 [running]> on host 684b6c366e0e
[2024-11-17T22:19:34.920+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bronze_to_gold_dag' AIRFLOW_CTX_TASK_ID='upload_raw_data_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T22:19:32.747734+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T22:19:32.747734+00:00'
[2024-11-17T22:19:34.921+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline_dag.py", line 16, in upload_raw_data_to_bronze
    df = pd.read_csv(raw_data_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/raw_data.csv'
[2024-11-17T22:19:34.930+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_to_gold_dag, task_id=upload_raw_data_to_bronze, execution_date=20241117T221932, start_date=20241117T221934, end_date=20241117T221934
[2024-11-17T22:19:34.936+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 8 for task upload_raw_data_to_bronze ([Errno 2] No such file or directory: '/opt/airflow/data/raw_data.csv'; 185)
[2024-11-17T22:19:34.971+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-11-17T22:19:34.989+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
